[package]
name = "butter2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
ndarray = "0.15.6"
num-complex = "0.4.4"
rustfft = "6.1.0"
fft2d = { version = "0.1.1", features = ["nalgebra"] }
nalgebra = "0.29"
itertools = "0.12.0"
